web:
  build: .
  command: 'bash -c ''/app/heroku/node/bin/npm start'''
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  links:
    - redis
    - mongo
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  volumes:
    - '.:/app/user'
  links:
    - redis  
    - mongo
mongo:
  image: mongo
  command: --smallfiles
  ports:
    - "27017:27017"
redis:
  image: redis:latest
