version: '2'
services:
  mongolab:
    image: mongo
  searchbox:
    image: elasticsearch
  web:
    build: .
    command: 'gulp serve'
    volumes:
        - ./:/app/user
    working_dir: /app/user
    environment:
      PORT: 3000
      MONGOLAB_URI: 'mongodb://mongolab:27017'
      SEARCHBOX_URL: 'searchbox:9200'
      APP_SECRET: 'very secret key!'
      ORIGINS_WHITELIST: 'localhost:4200'
    ports:
      - "3000:3000"
