version: '2'
services:
  mongolab:
    image: mongo
  searchbox:
    image: elasticsearch
  web:
    build: .
    command: 'ts-node server.ts'
    volumes:
        - ./:/app/user
    working_dir: /app/user
    environment:
      PORT: 3000
      MONGOLAB_URI: 'mongolab:27017'
      ELASTIC_URL: 'searchbox:9200'
    ports:
      - "3000:3000"
