export const TYPES = {
    Client: Symbol('Client'),
    PingServer: Symbol('PingServer'),
    SaveMessage: Symbol('SaveMessage'),
    QueryMessages: Symbol('QueryMessages'),
    CreateMD5: Symbol('CreateMD5'),
    CreateMessagesIndex: Symbol('CreateMessagesIndex'),
    LoginUser: Symbol('LoginUser'),
    GetMongoDB: Symbol('GetMongoDB'),
    CreateUser: Symbol('CreateUser'),
    Config: Symbol('Config'),
    QueryApplications: Symbol('QueryApplications'),
    CreateApplication: Symbol('CreateApplication'),
    GetMessageByHash: Symbol('GetMessageByHash'),
    CreateComment: Symbol('CreateComment'),
    GetComments: Symbol('GetComments'),
    GetApplication: Symbol('GetApplication'),
};